using Fhi.Samples.EndUser.Angular.BFFApi.Services.Models;
using Microsoft.IdentityModel.Tokens;
using System.Security.Cryptography;

namespace Fhi.Samples.EndUser.Angular.BFFApi.Services.DPoP
{
    /// <summary>
    /// Provides a single RSA key pair used for generating DPoP proofs.
    /// 
    /// This implementation stores the key pair in memory for the lifetime of the
    /// application instance. All DPoP proofs generated by this BFF will use the
    /// same key pair, meaning all access tokens issued by ID-porten will be bound
    /// to this key.
    ///
    /// This is appropriate for:
    /// - Backend-for-frontend (BFF) scenarios
    /// - Server-side token handling
    /// - Stateless frontend clients that never see the key
    ///
    /// Not appropriate for:
    /// - Per-user key binding (requires a per-session key store)
    /// - Multi-instance deployments without shared key storage
    ///
    /// If the application restarts, a new key pair is generated and previously
    /// issued DPoP-bound tokens will no longer be valid.
    /// </summary>
    public class InMemoryDPoPKeyStore : IDPoPKeyStore
    {
        private readonly DpopKeyPair _keys;

        public InMemoryDPoPKeyStore()
        {
            // Generate a new RSA key pair (private + public)
            // 2048 bits is the recommended minimum for DPoP.
            using var rsa = RSA.Create(2048);

            // Export the private key parameters for signing DPoP proofs
            var privateKey = new RsaSecurityKey(rsa.ExportParameters(includePrivateParameters: true))
            {
                // Optional but recommended: assign a KeyId (kid)
                KeyId = Guid.NewGuid().ToString("N")
            };

            // Export the public key parameters for embedding in the DPoP JWT header
            var publicKey = JsonWebKeyConverter.ConvertFromRSASecurityKey(
                new RsaSecurityKey(rsa.ExportParameters(includePrivateParameters: false))
                {
                    KeyId = privateKey.KeyId // ensure public + private share the same kid
                }
            );

            // Store the key pair for reuse
            _keys = new DpopKeyPair(privateKey, publicKey);
        }

        /// <summary>
        /// Returns the RSA key pair used for signing DPoP proofs.
        /// Since this implementation is in-memory, the same key pair is returned
        /// for every request for the lifetime of the application.
        /// </summary>
        public Task<DpopKeyPair> GetKeyPairAsync() => Task.FromResult(_keys);
    }
}